#!/usr/bin/env bash

#################################################################
# Script for deleting a virtual environment create with _switch_virtualenv.
#
# The venv is placed in a dedicated directory for holding venvs.
#################################################################

venv_name="$1"
if [ -z $venv_name ]; then
    echo "Usage: _delete_virtualenv <venv_name>"
    exit 1
fi

VENV_DIR="${VENV_DIR:-/home/$USER/.venvs}"
venv="$VENV_DIR/$venv_name"

if [ "$venv" == "$VIRTUAL_ENV" ]; then
    deactivate
fi
rm -rf $venv

