#!/usr/bin/env bash

#################################################################
# Script for setting up a python package.
#
# Sets up:
# - .gitignore
#################################################################

# Copy the .gitignore to current dir
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cp $script_dir/resources/Python.gitignore .gitignore

