#!/usr/bin/env bash

#################################################################
# Script for creating and activating a virtual envvironment.
#
# The venv is placed in a dedicated directory for holding venvs.
# Python3 is the default version.
#################################################################

venv_name="$1"
if [ -z $venv_name ]; then
    echo "Usage: _switch_virtualenv <venv_name>"
    exit 1
fi

VENV_DIR="${VENV_DIR:-/home/$USER/.venvs}"
venv="$VENV_DIR/$venv_name"

if [ -d "$venv" ]; then
    # venv exists; activate the venv
    . $venv/bin/activate
    if [ "$?" != 0 ]; then
        # Create then try again
        virtualenv -p python3 $venv
        . $venv/bin/activate
    fi
else
    # venv doesn't exist; create it
    virtualenv -p python3 $venv
    . $venv/bin/activate
fi

